### ISSUE TITLE
Filter & search catalog (Epic)

### ISSUE THREAD

**Issue by jolbax** [jolbax/osb-store#1]
**As a** user  
**I want to** search and filter the search catalog  
**So I can** quickly find and select the service I need
Recommended approach:

* Use the [Fuse.js](https://fusejs.io/) library (as it has typescript bindings)
* Create a [Vuex getter](https://vuex.vuejs.org/guide/getters.html#method-style-access) that takes the search input and filters catalog
* Use `lodash.debounce` method to make sure not fired too often
* Render catalog

Scope:

* [ ] define public component contract (can be done on Slite)
* [ ] \[ux\] From the perspective of the user, design two alternative user interfaces for searching with wireframes & mockups
* [ ] discuss and decide on one approach
* [ ] \[TDD\] Write tests

**Comment by jolbax** [comment]
Wireframe & Mockups can be found [here](https://drive.google.com/file/d/1J3Vuxqa1N5UatgHUvxTyEJg_qpxEorAT/view?usp=sharing[](url))
